//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramacionWeb3.Dominio.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva : Entidad
    {
        public new int Id { get; set; }
        public int CantPersonas { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdPaquete { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Paquete Paquete { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
